import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import java.io.StringReader
import java.util.Properties

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
}

abstract class GenerateWebBuildEnv : DefaultTask() {
    @get:Input
    abstract val environment: Property<String>

    @get:Input
    abstract val backendUrl: Property<String>

    @get:Input
    abstract val demo: Property<Boolean>

    @get:Input
    abstract val versionName: Property<String>

    @get:Input
    abstract val versionCode: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        // Validated here, not at configuration time, so unit tests and other tasks need no flags.
        val env = environment.get().trim().lowercase()
        val url = backendUrl.get()
        val demoRequested = demo.get()
        if (env !in listOf("dev", "stage", "prod")) {
            throw GradleException("kmpEnv must be dev, stage or prod, was '${environment.get()}'")
        }
        if (env == "dev" && url.isEmpty() && !demoRequested) {
            throw GradleException(
                "Web dev build needs a backend or demo mode. " +
                    "Run with -PkmpDemo=true or -PkmpBackendUrl=<url> (see docs/environments.md)."
            )
        }
        if (env != "dev" && (url.isNotEmpty() || demoRequested)) {
            throw GradleException(
                "Web $env build uses the fixed $env backend; remove -PkmpBackendUrl and -PkmpDemo."
            )
        }
        val code = versionCode.get().trim().toIntOrNull()
            ?: throw GradleException("Version code '${versionCode.get()}' is not a number")
        val name = versionName.get().trim()
        if (!Regex("^[0-9A-Za-z._+-]+$").matches(name)) {
            throw GradleException("VERSION_NAME '$name' may only contain letters, digits and . _ + -")
        }
        val dir = outputDir.get().asFile.resolve("com/anksoft/myapplication")
        dir.mkdirs()
        dir.resolve("WebBuildEnv.kt").writeText(
            """
            |package com.anksoft.myapplication
            |
            |// Generated by GenerateWebBuildEnv; do not edit.
            |internal object WebBuildEnv {
            |    const val ENVIRONMENT = "$env"
            |    const val BACKEND_URL = "$url"
            |    const val DEMO = $demoRequested
            |    const val VERSION_NAME = "$name"
            |    const val VERSION_CODE = $code
            |}
            |""".trimMargin()
        )
    }
}

// Version comes from the single source, <repo>/version.properties (also read by Android and iOS).
val versionProps = Properties().apply {
    load(
        StringReader(
            providers.fileContents(rootProject.layout.projectDirectory.file("version.properties")).asText.get()
        )
    )
}

// Environment: -PkmpEnv=dev|stage|prod (default dev). Checked when generateWebBuildEnv runs.
// dev needs -PkmpDemo=true or -PkmpBackendUrl=http://localhost:8081/api/v1/; stage and prod accept neither.
val kmpBackendUrl: String = providers.gradleProperty("kmpBackendUrl").orElse("").get().trim()
require(kmpBackendUrl.isEmpty() || Regex("^https?://[^\\s\"\\\\$]+$").matches(kmpBackendUrl)) {
    "kmpBackendUrl must start with http:// or https:// and contain no spaces, quotes, backslashes or '$'"
}

val generateWebBuildEnv = tasks.register<GenerateWebBuildEnv>("generateWebBuildEnv") {
    environment.set(providers.gradleProperty("kmpEnv").orElse("dev"))
    backendUrl.set(kmpBackendUrl)
    demo.set(providers.gradleProperty("kmpDemo").map { it.trim().toBoolean() }.orElse(false))
    versionName.set(versionProps.getProperty("VERSION_NAME", "").trim())
    versionCode.set(
        providers.gradleProperty("kmpVersionCode").orElse(versionProps.getProperty("VERSION_CODE", "")).map { it.trim() }
    )
    outputDir.set(layout.buildDirectory.dir("generated/webBuildEnv"))
}

kotlin {
    js {
        browser()
        binaries.executable()
    }

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser()
        binaries.executable()
    }

    sourceSets {
        // webMain comes from the default hierarchy template and is created lazily.
        matching { it.name == "webMain" }.configureEach {
            kotlin.srcDir(generateWebBuildEnv.map { it.outputDir })
        }
        commonMain.dependencies {
            implementation(project(":shared"))

            implementation(libs.compose.ui)
            // main() calls initKoin, whose return type comes from koin-core.
            implementation(libs.koin.core)
        }
    }
}