import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
}

abstract class GenerateWebBuildEnv : DefaultTask() {
    @get:Input
    abstract val backendUrl: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val url = backendUrl.get()
        val dir = outputDir.get().asFile.resolve("com/anksoft/myapplication")
        dir.mkdirs()
        dir.resolve("WebBuildEnv.kt").writeText(
            """
            |package com.anksoft.myapplication
            |
            |// Generated by GenerateWebBuildEnv; do not edit.
            |internal object WebBuildEnv {
            |    const val BACKEND_URL = "$url"
            |}
            |""".trimMargin()
        )
    }
}

// Optional backend: -PkmpBackendUrl=http://localhost:8081/api/v1/ (empty keeps demo mode).
val kmpBackendUrl: String = providers.gradleProperty("kmpBackendUrl").orElse("").get().trim()
require(kmpBackendUrl.isEmpty() || Regex("^https?://[^\\s\"\\\\$]+$").matches(kmpBackendUrl)) {
    "kmpBackendUrl must start with http:// or https:// and contain no spaces, quotes, backslashes or '$'"
}

val generateWebBuildEnv = tasks.register<GenerateWebBuildEnv>("generateWebBuildEnv") {
    backendUrl.set(kmpBackendUrl)
    outputDir.set(layout.buildDirectory.dir("generated/webBuildEnv"))
}

kotlin {
    js {
        browser()
        binaries.executable()
    }

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser()
        binaries.executable()
    }

    sourceSets {
        named("webMain") {
            kotlin.srcDir(generateWebBuildEnv.map { it.outputDir })
        }
        commonMain.dependencies {
            implementation(project(":shared"))

            implementation(libs.compose.ui)
            // main() calls initKoin, whose return type comes from koin-core.
            implementation(libs.koin.core)
        }
    }
}